In [1]:
import pandas as pd
import numpy as np

In [10]:
lt1=[]
lt2=[]
lt3=[]
lt4=[]
lt5=[]
lt6=[]
lt7=[]
lt8=[]
lt1=np.random.randint(2, size=2797)
lt2=np.random.randint(2, size=2797)
lt3=np.random.randint(2, size=2797)
lt4=np.random.randint(2, size=2797)
lt5=np.random.randint(2, size=2797)
lt6=np.random.randint(1,5, size=2797)
lt7=np.random.randint(2, size=2797)
lt8=np.random.randint(2, size=2797)

In [13]:
df=pd.read_csv('Second.csv')

In [14]:

df['sputum']=lt1
df['x-ray']=lt2
df['genes']=lt3
df['cavitation']=lt4
df['hiv']=lt5
df['cd4+']=lt7
df['regimen']=lt6
df['cured']=lt8

In [15]:
df

         id  sputum  x-ray  genes  cavitation  hiv  cd4+  regimen  cured
0     10000       1      0      1           0    0     0        4      0
1     10001       1      1      1           0    0     0        1      1
2     10002       1      0      0           1    1     1        2      0
3     10003       1      0      0           1    1     1        4      0
4     10004       0      0      0           0    0     1        1      0
5     10005       1      1      0           0    1     1        1      1
6     10006       0      1      1           1    1     1        2      1
7     10007       1      0      0           0    1     1        2      0
8     10008       1      0      1           1    1     1        3      1
9     10009       0      1      1           1    0     1        3      0
10    10010       1      0      1           0    1     1        3      0
11    10011       1      1      1           1    0     0        1      0
12    10012       0      1      1           0    0     0        1      1
13    10013       1      1      0           0    1     0        1      0
14    10014       0      1      0           0    0     1        2      0
15    10015       1      1      0           0    0     0        3      1
16    10016       1      0      0           1    1     0        4      0
17    10017       1      1      1           0    1     1        1      1
18    10018       1      1      1           1    1     1        3      0
19    10019       0      0      0           1    1     0        4      1
20    10020       1      0      0           1    1     0        3      1
21    10021       1      0      1           1    0     1        3      0
22    10022       0      0      0           1    0     0        2      0
23    10023       1      1      0           0    0     0        4      1
24    10024       0      0      0           1    1     0        4      0
25    10025       1      0      1           0    0     1        1      1
26    10026       0      0      0           0    1     1        1      0
27    10027       1      0      0           1    0     1        4      0
28    10028       0      0      1           1    1     0        1      0
29    10029       0      1      1           1    0     1        2      0
...     ...     ...    ...    ...         ...  ...   ...      ...    ...
2767  12767       1      1      0           1    1     1        3      1
2768  12768       0      1      1           0    1     0        4      0
2769  12769       1      1      1           0    0     1        2      0
2770  12770       1      0      0           0    0     0        1      1
2771  12771       0      1      1           0    0     1        4      1
2772  12772       0      0      1           1    0     0        2      0
2773  12773       0      1      0           1    0     0        4      1
2774  12774       0      1      1           1    0     0        3      1
2775  12775       1      0      1           1    1     0        2      1
2776  12776       1      1      1           1    0     0        1      0
2777  12777       1      0      1           0    1     0        1      1
2778  12778       1      0      1           0    0     0        4      0
2779  12779       0      0      1           0    1     1        1      1
2780  12780       1      1      1           0    1     0        1      1
2781  12781       0      0      0           1    0     0        4      1
2782  12782       1      0      0           0    1     1        1      0
2783  12783       0      0      0           0    0     1        1      1
2784  12784       0      0      1           1    1     1        2      0
2785  12785       0      0      0           0    1     0        1      1
2786  12786       0      1      1           0    1     1        3      1
2787  12787       0      0      0           0    0     1        1      1
2788  12788       0      0      1           0    0     0        4      1
2789  12789       0      0      0           0    0     0        3      0
2790  12790       1      0      0           0    1     0        2      1
2791  12791       1      1      0           0    1     1        2      0
2792  12792       0      1      1           1    1     1        4      0
2793  12793       1      0      1           1    1     0        4      0
2794  12794       1      0      1           1    1     0        3      1
2795  12795       0      0      0           1    1     0        2      0
2796  12796       0      1      0           0    0     0        4      0

[2797 rows x 9 columns]

In [29]:
df.to_csv("Result.csv",index=False)